### ISSUE TITLE
TV recommendation codelabe project does not build after cloning

### ISSUE THREAD

**Issue by marcbaechinger** [googlecodelabs/tv-recommendations#1]
I tried to do the codelab and failed with the following. Am I doing something wrong?

git clone https://github.com/googlecodelabs/tv-recommendations.git
cd tv-recommendations
./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'tv-recommendations'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:3.0.0-alpha1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0-alpha1/gradle-3.0.0-alpha1.pom
         https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.0-alpha1/gradle-3.0.0-alpha1.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 1s

Expected behaviour: project builds after download without modification.

**Comment by marcbaechinger** [comment]
Adding the maven repository helped for me.

buildscript {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
....

to make it run without exiting on lint errors I also added:
android {
    lintOptions {
        abortOnError false
    }
}

to the gradle file of each step

**Comment by benbaxter** [comment]
The gradle plugin needs to be upgraded from the alpha version. I will clean this up shortly 😅

**Comment by benbaxter** [comment]
I updated the gradle files. It is building after cloning for me. I am using Android Studio 3.0 beta2 to test with.
